In [44]:
import sqlite3

# connect to our database
conn = sqlite3.connect('C:/Users/jackr/Desktop/sis_db_2700')

# drop the "with closing" since there is no need for a context manager with the cursor
c = conn.cursor()
user_sid = input("Enter a Student ID: ")
sql = '''SELECT studentCourse.sid, studentCourse.cid, Course.creditHours
        FROM Course
        JOIN studentCourse ON Course.cid = studentCourse.cid
        WHERE studentCourse.sid = ?'''
c.execute(sql, (user_sid,))

# get all rows from the SELECT query
rows = c.fetchall()

# display the selected rows
for row in rows:
    print(row)

# close the cursor and the database connection
c.close()
conn.close()

Enter a Student ID: B0001235
('B0001235', 'CS2250', 3)
('B0001235', 'DATA1000', 3)

In [43]:
import sqlite3

# connect to our database
conn = sqlite3.connect('C:/Users/jackr/Desktop/sis_db_2700')

# drop the "with closing" since there is no need for a context manager with the cursor
c = conn.cursor()

sql = '''SELECT * FROM studentCourse'''
c.execute(sql)

# get all rows from the SELECT query
rows = c.fetchall()

# display the selected rows
for row in rows:
    print(row)

# close the cursor and the database connection
c.close()
conn.close()

('B0001235', 'CS2250')
('B0001235', 'DATA1000')
('B0003001', 'CS1280')
('B0003001', 'CS1290')
('B0002001', 'CS1280')
('B0002001', 'CS2700')
('B0001234', 'DATA3500')
('B0001236', 'CS1280')
('B0001236', 'CS1290')

In [ ]:
#!/usr/bin/env python
# coding: utf-8

# In[1]:


# GUI coding for Student Registration function

# Import Module
from tkinter import *

# Function for clearing the contents of all entry boxes 
def clear_all() :

	# whole content of entry boxes is deleted 
	sid_field.delete(0, END) 
	cid_field.delete(0, END)

#  PLACE FUNCTION HERE TO PERFORM SQL INSERT

def student_search():
    global sid_field
    global sname_field

# create root window
root = Tk()

# root window title and dimension
root.title("Student Registration")
# Set geometry(widthxheight)
root.geometry('475x200')
root.resizable(0, 0)
# adding labels to the root window
lbl1 = Label(root, text = "Student ID")
lbl1.grid()
lbl2 = Label(root, text = "Student Name:")
lbl2.grid()
lbl3 = Label(root, text = "Course Title")
lbl3.grid()
lbl4 = Label(root, text = "Credit Hours")
lbl4.grid()

sid_field = Entry(root) 
sname_field = Entry(root)
course1 = Label(root,bg="white", width=20)
course2 = Label(root,bg="white", width=20)
course3 = Label(root,bg="white", width=20)

ch1= Label(root,bg="white", width=20)
ch2= Label(root,bg="white", width=20)
ch3= Label(root,bg="white", width=20)

sid_field.grid(row = 1, column = 1, padx = 10, pady = 10) 
sname_field.grid(row = 2, column = 1, padx = 10, pady = 10)


lbl1.grid(row = 1, column = 0, padx = 10, pady = 10) 
lbl2.grid(row = 2, column = 0, padx = 10, pady = 10)
lbl3.grid(row = 3, column = 0, padx = 10, pady = 10)
lbl4.grid(row = 3, column = 3, padx = 10, pady =10)

course1.grid(row = 4, column = 0, padx = 10, pady = 1)
course2.grid(row = 5, column = 0, padx = 10, pady = 1)
course3.grid(row = 6, column = 0, padx = 10, pady = 1)


ch1.grid(row = 4, column = 3, padx = 10, pady = 1)
ch2.grid(row = 5, column = 3, padx = 10, pady = 1)
ch3.grid(row = 6, column = 3, padx = 10, pady = 1)
# Execute Tkinter
root.mainloop()


# In[ ]: